
stages:
  - sast
  - sca
  - secrets
  - dast

variables:
  SEMGREP_RULES: "p/default"

sast:semgrep:
  stage: sast
  image: returntocorp/semgrep:latest
  script:
    - semgrep ci --config "$SEMGREP_RULES" --sarif --output semgrep.sarif
  artifacts:
    paths:
      - semgrep.sarif
    reports:
      sast: semgrep.sarif
  only:
    - merge_requests
    - main

sast:codeql:
  # CodeQL is GitHub-native; on GitLab you can run CodeQL CLI container if licensed,
  # or rely on Semgrep. If you maintain a CodeQL container, add it here.
  stage: sast
  image: ghcr.io/github/codeql-container:latest
  script:
    - /opt/codeql/codeql database create db --language=javascript,python,java --source-root .
    - /opt/codeql/codeql database analyze db --format=sarifv2 --output codeql.sarif
  artifacts:
    paths: [ codeql.sarif ]
    reports:
      sast: codeql.sarif
  only:
    - merge_requests
    - main

secrets:gitleaks:
  stage: secrets
  image: zricethezav/gitleaks:latest
  script:
    - gitleaks detect --source . --report-format sarif --report-path gitleaks.sarif
  artifacts:
    paths:
      - gitleaks.sarif
    reports:
      sast: gitleaks.sarif
  only:
    - merge_requests
    - main

sca:trivy-fs:
  stage: sca
  image: aquasec/trivy:latest
  script:
    - trivy fs --format sarif -o trivy-fs.sarif --severity HIGH,CRITICAL .
    - test $(jq '.runs[0].results | length' trivy-fs.sarif) -eq 0
  artifacts:
    paths:
      - trivy-fs.sarif
    reports:
      dependency_scanning: trivy-fs.sarif
  only:
    - merge_requests
    - main

sca:trivy-image:
  stage: sca
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - apk add --no-cache curl jq
    - curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s --
    - ./bin/trivy image --format sarif -o trivy-image.sarif --severity HIGH,CRITICAL $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - test $(jq '.runs[0].results | length' trivy-image.sarif) -eq 0
  artifacts:
    paths:
      - trivy-image.sarif
    reports:
      dependency_scanning: trivy-image.sarif
  only:
    - merge_requests
    - main

dast:zap-baseline:
  stage: dast
  image: ghcr.io/zaproxy/zaproxy:stable
  script:
    - zap-baseline.py -t "$DAST_TARGET_URL" -r zap-report.html -J zap.json
    - cat zap.json | jq '.'
  artifacts:
    paths:
      - zap-report.html
      - zap.json
  only:
    - main
  rules:
    - if: '$DAST_TARGET_URL'
